print("===================================")
print("\\a bell")
print("\\b back space            --> 后退")
print("\\f form feed             --> 换页")
print("\\n new line              --> 换行")
print("\\r carriage return       --> 回车")
print("\\t horizontal tab        --> 制表 横向")
print("\\v vertical tab          --> 制表 纵向")
print("\\\\ backslash             --> \"\\\"")
print("\\\" double quote          --> 双引号")
print("\\' single quote          --> 单引号")
print("\\[ left square bracket   --> 左中括号")
print("\\] right square bracket  --> 右中括号")
print("===================================")

print("one line\nnext line\n\"in quotes\", 'in quotes'")
print('a backslash inside quotes:\'\\\'')
print("a simpler way:'\\'")

